/* global devs, level, boot, advance, flush, cloud, addDevice, door, feeder, registry, files, check, svc, val, read, byName, logHas, logs, out, failures, passes, hap */

async function main() {
  var CFG = { name: 'Omlet', bearerToken: 'good_token', countryCode: 'GB' };

  out('1. Fresh install: two doors, a feeder and a fan on one account');
  addDevice(door('DOOR1', 'Green Coop', { light: true }));
  addDevice(door('DOOR2', 'Blue Coop', { mains: true }));
  addDevice(feeder('FEED1', 'Big Feeder', 55));
  cloud.devices.FAN1 = { deviceId: 'FAN1', name: 'Coop Fan', deviceType: 'Fan', state: {} };
  var b = await boot(CFG);
  await advance(10000);
  check(devs().length === 3, 'three devices registered (fan skipped), got ' + devs().length);
  check(logHas(/Skipping "Coop Fan".*not supported/), 'fan logged as unsupported');
  var g = byName('Green Coop'), bl = byName('Blue Coop'), f = byName('Big Feeder');
  check(g && bl && f, 'accessories named after the Omlet devices');
  check(g.context.deviceId === 'DOOR1' && bl.context.deviceId === 'DOOR2' && f.context.kind === 'feeder', 'device IDs and kinds recorded in context');
  check(!!svc(g, 'Lightbulb') && !svc(bl, 'Lightbulb'), 'light only on the door that has one');
  check(!!svc(g, 'Battery') && !svc(bl, 'Battery'), 'battery only on the battery-powered door');
  check(val(g, 'GarageDoorOpener', 'CurrentDoorState') === 1, 'Green Coop reports closed');
  check(!svc(f, 'HumiditySensor') && !!level('Big Feeder'), 'feed level is its own accessory, not on the feeder');
  check(level('Big Feeder').services.length === 2 && !!svc(level('Big Feeder'), 'HumiditySensor'), 'feed level accessory has one service (plus info), so Home cannot group it');
  check(await read(level('Big Feeder'), 'HumiditySensor', 'CurrentRelativeHumidity') === 55, 'feed level 55%');
  check(registry.length === 4, 'four accessories including the feed level tile');
  check(await read(f, 'OccupancySensor', 'OccupancyDetected') === 0, 'feed not low at 55%');
  check(await read(f, 'ContactSensor', 'ContactSensorState') === 0, 'feeder door closed');
  check(!!svc(f, 'Battery'), 'feeder battery shown');
  check(logHas(/\[Big Feeder\] \[Feeder\] Feed level 55%, door closed\. Full state:.*feedLevel/), 'first feeder reading logged with level, door and full state');
  check(logHas(/Feeder initialized \(Feed Low alert threshold: 20%/), 'startup line names the threshold as a threshold');
  var polled = cloud.requests.filter(function (r) { return /^GET \/api\/v1\/device\//.test(r); });
  check(polled.some(function (r) { return /DOOR1$/.test(r); }) && polled.some(function (r) { return /DOOR2$/.test(r); }) && polled.some(function (r) { return /FEED1$/.test(r); }), 'each device polled on its own ID');
  check(files['/hb/omlet-multi-tokens.json'] && JSON.parse(files['/hb/omlet-multi-tokens.json']).bearerToken === 'good_token', 'token saved to our own storage file');
  check(JSON.parse(files['/hb/config.json']).platforms[0].bearerToken === undefined, 'token removed from config.json');

  out('2. Commands go to the right door');
  cloud.requests = [];
  await svc(bl, 'GarageDoorOpener').getCharacteristic(hap.Characteristic.TargetDoorState).setter(0);
  check(cloud.requests.indexOf('POST /api/v1/device/DOOR2/action/open') >= 0, 'open sent to Blue Coop only');
  check(cloud.requests.every(function (r) { return !/DOOR1\/action/.test(r); }), 'Green Coop untouched');
  await svc(g, 'Lightbulb').getCharacteristic(hap.Characteristic.On).setter(true);
  check(cloud.devices.DOOR1.state.light.state === 'on', 'Green Coop light switched on');
  await advance(60000);
  check(val(bl, 'GarageDoorOpener', 'CurrentDoorState') === 0, 'Blue Coop now reports open');
  check(val(g, 'GarageDoorOpener', 'CurrentDoorState') === 1, 'Green Coop still closed');

  out('3. Feed runs low');
  cloud.devices.FEED1.state.feeder.feedLevel = 12;
  await advance(5 * 60 * 1000);
  check(val(level('Big Feeder'), 'HumiditySensor', 'CurrentRelativeHumidity') === 12, 'feed level updated to 12%');
  check(val(f, 'OccupancySensor', 'OccupancyDetected') === 1, 'Feed Low triggered below 20%');
  var feederPolls = cloud.requests.filter(function (r) { return r === 'GET /api/v1/device/FEED1'; }).length;
  check(feederPolls <= 2, 'feeder polled no more than every 5 minutes (' + feederPolls + ' polls in ~6 min)');

  out('4. A third door is added while running');
  addDevice(door('DOOR3', 'New Coop', { light: true }));
  await advance(60 * 60 * 1000);
  check(!!byName('New Coop') && devs().length === 4, 'picked up by hourly rediscovery without restart');

  out('5. Restart: accessories restored from cache, not duplicated');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(CFG);
  await advance(15000);
  check(devs().length === 4, 'still four accessories, got ' + devs().length);
  check(b.platform.handlers.size === 4, 'four handlers running');
  check(logHas(/Using saved API key/), 'used the stored key after config.json was cleaned');

  out('6. One door replaced (new device ID): accessory kept and re-pointed');
  delete cloud.devices.DOOR2;
  addDevice(door('DOOR2B', 'Blue Coop', { mains: true }));
  b.platform.handlers.forEach(function (h) { h.stop(); });
  var blueBefore = byName('Blue Coop');
  b = await boot(CFG);
  await advance(15000);
  check(devs().length === 4, 'no accessory added or lost, got ' + devs().length);
  check(byName('Blue Coop') === blueBefore && blueBefore.context.deviceId === 'DOOR2B', 'same HomeKit accessory now on DOOR2B');
  check(logHas(/has been replaced by "Blue Coop" \(DOOR2B\)/), 'swap logged');

  out('7. Two doors swapped at once: no guessing');
  delete cloud.devices.DOOR1; delete cloud.devices.DOOR3;
  addDevice(door('DOOR1B', 'Green Coop 2', {})); addDevice(door('DOOR3B', 'New Coop 2', {}));
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(CFG);
  await advance(15000);
  check(!byName('Green Coop') && !byName('New Coop'), 'old accessories removed');
  check(!!byName('Green Coop 2') && !!byName('New Coop 2'), 'new accessories added');
  check(devs().length === 4, 'four accessories, got ' + devs().length);

  out('8. Excluding a device');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { excludeDevices: ['DOOR3B'] }));
  await advance(15000);
  check(!byName('New Coop 2') && devs().length === 3, 'excluded door removed from HomeKit');
  check(logHas(/Skipping "New Coop 2".*excluded/), 'exclusion logged');

  out('9. Omlet unreachable at startup');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  cloud.failDiscovery = true;
  var EXCL = Object.assign({}, CFG, { excludeDevices: ['DOOR3B'] });
  cloud.requests = [];
  b = await boot(EXCL);
  await advance(15000);
  check(cloud.requests.indexOf('GET /api/v1/device/DOOR2B') >= 0, 'cached door polled while discovery is down');
  check(b.platform.handlers.size === 3, 'cached devices started anyway (' + b.platform.handlers.size + ')');
  check(devs().length === 3, 'nothing removed while discovery is failing');
  check(val(byName('Blue Coop'), 'GarageDoorOpener', 'CurrentDoorState') === 1, 'cached door still polled and reporting');
  cloud.failDiscovery = false;
  await advance(61000);
  check(logHas(/Found an API key|Using saved API key/) && b.platform.initialSyncDone, 'discovery retried and succeeded');
  check(!byName('New Coop 2') && devs().length === 3, 'still honours exclusion after recovery');

  out('10. Door replaced while running (404 on poll)');
  delete cloud.devices['DOOR1B'];
  addDevice(door('DOOR1C', 'Green Coop 3', {}));
  var greenAcc = byName('Green Coop 2');
  await advance(60000);
  check(greenAcc.context.deviceId === 'DOOR1C', 'running accessory re-pointed at the single new door');
  check(b.platform.handlers.get('DOOR1C') && !b.platform.handlers.get('DOOR1B'), 'handler re-keyed');

  out('11. Migration from the single-door plugin');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0;
  files['/hb/omlet-coop-tokens.json'] = JSON.stringify({ bearerToken: 'good_token', deviceId: 'DOOR2B' });
  b = await boot({ name: 'Omlet', countryCode: 'GB' });
  await advance(15000);
  check(logHas(/Found an API key saved by the Omlet Coop plugin/), 'legacy key imported');
  check(devs().length === 4, 'all four devices set up from the imported key, got ' + devs().length);
  check(JSON.parse(files['/hb/omlet-multi-tokens.json']).bearerToken === 'good_token', 'imported key saved to our storage once it worked');


  out('12. Two doors removed at runtime, one new door added: no guessing');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0; cloud.devices = {};
  addDevice(door('RA', 'Coop A', {})); addDevice(door('RB', 'Coop B', {}));
  b = await boot(CFG);
  await advance(15000);
  var accA = byName('Coop A'), accB = byName('Coop B');
  delete cloud.devices.RA; delete cloud.devices.RB;
  addDevice(door('RBNEW', 'Coop B replacement', {}));
  await advance(60000);
  out('   Coop A now -> ' + accA.context.deviceId + ', Coop B now -> ' + accB.context.deviceId);
  check(accA.context.deviceId !== 'RBNEW' && accB.context.deviceId !== 'RBNEW', 'neither missing door takes the new one');

  out('13. Old device ID returns after a swap');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0; cloud.devices = {};
  addDevice(door('SA', 'Coop A', {})); addDevice(door('SB', 'Coop B', {}));
  b = await boot(CFG); await advance(15000);
  b.platform.handlers.forEach(function (h) { h.stop(); });
  delete cloud.devices.SB; addDevice(door('SBNEW', 'Coop B new', {}));
  b = await boot(CFG); await advance(15000);
  var accB2 = byName('Coop B');
  check(accB2.context.deviceId === 'SBNEW', 'swap happened');
  // old door comes back (e.g. re-shared into the account)
  cloud.devices = {}; addDevice(door('SB', 'Coop B old', {})); addDevice(door('SA', 'Coop A', {})); addDevice(door('SBNEW', 'Coop B new', {}));
  await advance(60 * 60 * 1000);
  var uuids = registry.map(function (a) { return a.UUID; });
  var dup = uuids.filter(function (u, i) { return uuids.indexOf(u) !== i; });
  check(dup.length === 0, 'no duplicate UUIDs registered (dups: ' + dup.join(',') + ')');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  check(!!byName('Coop B old') && byName('Coop B old').context.deviceId === 'SB', 'returning old door gets its own accessory');
  // restart with SB listed before SBNEW
  b = await boot(CFG); await advance(15000);
  check(accB2.context.deviceId === 'SBNEW', 'swapped accessory still bound to SBNEW after restart, got ' + accB2.context.deviceId);

  out('14. Feed level shown as a light bulb');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0; cloud.devices = {};
  addDevice(feeder('FEEDB', 'Scoops', 64));
  b = await boot(Object.assign({}, CFG, { feedLevelDisplay: 'lightbulb' }));
  await advance(15000);
  var sc = byName('Scoops');
  var scl = level('Scoops');
  check(!!svc(scl, 'Lightbulb') && !svc(scl, 'HumiditySensor') && !svc(sc, 'Lightbulb'), 'feed level tile is a light bulb, on its own accessory');
  check(svc(scl, 'Lightbulb').primary === true, 'bulb is the primary service');
  check(!!svc(sc, 'OccupancySensor'), 'Feed Low still present');
  check(val(scl, 'Lightbulb', 'Brightness') === 64 && val(scl, 'Lightbulb', 'On') === true, 'bulb on at 64% brightness');
  check(await read(scl, 'Lightbulb', 'Brightness') === 64, 'brightness read returns the feed level');
  var bulb = svc(scl, 'Lightbulb');
  bulb.getCharacteristic(hap.Characteristic.On).value = false;
  await bulb.getCharacteristic(hap.Characteristic.On).setter(false);
  await advance(1000);
  check(val(scl, 'Lightbulb', 'On') === true, 'switching it off is reverted');
  bulb.getCharacteristic(hap.Characteristic.Brightness).value = 10;
  await bulb.getCharacteristic(hap.Characteristic.Brightness).setter(10);
  await advance(1000);
  check(val(scl, 'Lightbulb', 'Brightness') === 64, 'dragging the brightness is reverted');
  check(cloud.requests.every(function (r) { return !/FEEDB\/action/.test(r); }), 'nothing is ever sent to the feeder');
  cloud.devices.FEEDB.state.feeder.feedLevel = 0;
  await advance(5 * 60 * 1000);
  check(val(scl, 'Lightbulb', 'On') === false && val(sc, 'Occupancy' + 'Sensor', 'OccupancyDetected') === 1, 'empty feeder: bulb off and Feed Low triggered');

  out('15. Switching display mode on a cached feeder');
  cloud.devices.FEEDB.state.feeder.feedLevel = 40;
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { feedLevelDisplay: 'off' }));
  await advance(15000);
  check(byName('Scoops') === sc, 'same accessory kept');
  check(!level('Scoops') && !!svc(sc, 'OccupancySensor'), 'off: feed level accessory removed, Feed Low kept');
  check(registry.every(function (a) { return !(a.context && a.context.role); }), 'feed level tile unregistered from HomeKit');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(CFG);
  await advance(15000);
  check(!!level('Scoops') && !!svc(level('Scoops'), 'HumiditySensor') && !svc(level('Scoops'), 'Lightbulb') && val(level('Scoops'), 'HumiditySensor', 'CurrentRelativeHumidity') === 40, 'default: feed level tile back, as humidity at 40%');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { feedLevelDisplay: 'banana' }));
  await advance(15000);
  check(logHas(/Invalid feedLevelDisplay "banana", using "humidity"/) && !!svc(level('Scoops'), 'HumiditySensor'), 'invalid setting falls back to humidity');

  out('16. Light level sensors');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0; cloud.devices = {};
  addDevice(door('LD1', 'Dark Coop', { lux: 0 })); addDevice(door('LD2', 'Bright Coop', { lux: 66 }));
  addDevice(feeder('LF1', 'Lit Feeder', 30));
  b = await boot(CFG);
  await advance(15000);
  var dk = byName('Dark Coop'), br = byName('Bright Coop'), lf = byName('Lit Feeder');
  check(!!svc(dk, 'LightSensor') && !!svc(br, 'LightSensor') && !!svc(lf, 'LightSensor'), 'light sensor on both doors and the feeder');
  check(val(br, 'LightSensor', 'CurrentAmbientLightLevel') === 66, 'door light level 66');
  check(val(lf, 'LightSensor', 'CurrentAmbientLightLevel') === 40, 'feeder light level 40');
  check(val(dk, 'LightSensor', 'CurrentAmbientLightLevel') === 0.0001, 'zero clamped to HomeKit minimum');
  check(svc(br, 'GarageDoorOpener').linked.indexOf(svc(br, 'LightSensor')) >= 0, 'linked to the door');
  cloud.devices.LD2.state.door.lightLevel = 12;
  await advance(31000);
  check(val(br, 'LightSensor', 'CurrentAmbientLightLevel') === 12, 'updates on the next poll');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { enableLightLevel: 'off' }));
  await advance(15000);
  check(!svc(dk, 'LightSensor') && !svc(br, 'LightSensor') && !svc(lf, 'LightSensor'), 'enableLightLevel off removes them');

  out('17. Feed level shown as the battery');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { feedLevelDisplay: 'battery' }));
  await advance(15000);
  check(!!svc(lf, 'Battery') && !level('Lit Feeder'), 'battery mode: level on the feeder battery, no separate tile');
  check(val(lf, 'Battery', 'BatteryLevel') === 30 && val(lf, 'Battery', 'Name') === 'Lit Feeder Feed Level', 'battery tile shows feed level 30%, named Feed Level');
  check(await read(lf, 'Battery', 'BatteryLevel') === 30, 'battery read returns feed level');
  cloud.devices.LF1.state.feeder.feedLevel = 15;
  await advance(5 * 60 * 1000);
  check(val(lf, 'Battery', 'StatusLowBattery') === 1 && val(lf, 'OccupancySensor', 'OccupancyDetected') === 1, 'low warning and Feed Low both trip at 15%');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { feedLevelDisplay: 'battery', enableBattery: 'off' }));
  await advance(15000);
  check(!!svc(lf, 'Battery'), 'battery mode keeps the tile even with Battery Status set to hide');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(CFG);
  await advance(15000);
  check(val(lf, 'Battery', 'BatteryLevel') === 64 && val(lf, 'Battery', 'Name') === 'Lit Feeder Battery', 'back to humidity mode: battery tile shows the real battery again');
  check(!!level('Lit Feeder'), 'feed level tile back');

  out('18. Feed level tile follows its feeder');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  Object.keys(files).forEach(function (k) { delete files[k]; });
  registry.length = 0; cloud.devices = {};
  addDevice(feeder('CF1', 'Front Feeder', 70)); addDevice(feeder('CF2', 'Back Feeder', 30));
  b = await boot(CFG);
  await advance(15000);
  check(!!level('Front Feeder') && !!level('Back Feeder') && registry.length === 4, 'each feeder gets its own level tile');
  check(val(level('Front Feeder'), 'HumiditySensor', 'CurrentRelativeHumidity') === 70 && val(level('Back Feeder'), 'HumiditySensor', 'CurrentRelativeHumidity') === 30, 'each tile shows its own feeder');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(CFG);
  await advance(15000);
  check(registry.length === 4, 'restart: no duplicate level tiles, got ' + registry.length);
  check(await read(level('Front Feeder'), 'HumiditySensor', 'CurrentRelativeHumidity') === 70, 'restored tile still reads live');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  b = await boot(Object.assign({}, CFG, { excludeDevices: ['CF2'] }));
  await advance(15000);
  check(!byName('Back Feeder') && !level('Back Feeder') && registry.length === 2, 'excluding a feeder removes its level tile too');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  delete cloud.devices.CF1; addDevice(feeder('CF1B', 'Front Feeder', 55));
  var frontLevel = level('Front Feeder');
  b = await boot(Object.assign({}, CFG, { excludeDevices: ['CF2'] }));
  await advance(15000);
  check(level('Front Feeder') === frontLevel && val(frontLevel, 'HumiditySensor', 'CurrentRelativeHumidity') === 55, 'replaced feeder keeps its level tile, now reading the new device');
  check(registry.length === 2, 'still two accessories, got ' + registry.length);
  b.platform.handlers.forEach(function (h) { h.stop(); });
  cloud.failDiscovery = true;
  b = await boot(Object.assign({}, CFG, { excludeDevices: ['CF2'] }));
  await advance(15000);
  check(!!level('Front Feeder') && registry.length === 2, 'Omlet unreachable: level tile kept');
  cloud.failDiscovery = false;

  out('19. Upgrading from 1.1.0 (level services on the feeder)');
  b.platform.handlers.forEach(function (h) { h.stop(); });
  var ff = byName('Front Feeder');
  registry = registry.filter(function (a) { return !(a.context && a.context.role); });
  var old = ff.addService(hap.Service.Lightbulb, 'Front Feeder Feed Level');
  b = await boot(Object.assign({}, CFG, { excludeDevices: ['CF2'], feedLevelDisplay: 'lightbulb' }));
  await advance(15000);
  check(!svc(ff, 'Lightbulb') && !!svc(level('Front Feeder'), 'Lightbulb'), 'old bulb removed from the feeder, new one on its own tile');

  out('');
  out(passes + ' passed, ' + failures + ' failed');
  if (failures) {
    out('--- log tail ---');
    logs.slice(-40).forEach(function (l) { out(l); });
  }
}
main().catch(function (e) { out('CRASH ' + e + '\n' + e.stack); });
